# Generated by Django 3.2.7 on 2021-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.FloatField(),
        ),
    ]
