# Generated by Django 3.2.7 on 2021-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0002_alter_people_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.CharField(max_length=100),
        ),
    ]
